### ISSUE TITLE
Heart rate not showed on overlay

### ISSUE THREAD

**Issue by kirarutami** [SuspiciousLookingOwl/mi-band-heart-rate-overlay#1]
i already installed Automate and Tools and Mi Band and followed the instruction. Input my PC IP address and my band already notified, but it wasn't connected to the OBS overlay. can you help?

**Comment by kirarutami** [comment]
@SuspiciousLookingOwl

**Comment by SuspiciousLookingOwl** [comment]
Does the desktop application shows any received heart rate like this?
![image](https://user-images.githubusercontent.com/32597776/166908029-e4868660-2389-4705-91bc-ddc2da891ba7.png)

If not, then your phone probably can't connect to your PC

1. Make sure that your phone and PC is connected to the same network (e.g. connected to a same Wi-Fi)
2. Make sure that you entered the correct PC local IP address

To make sure that your phone can connect to your PC, you can use an app like [Ping](https://play.google.com/store/apps/details?id=net.WisdomStar.Ping&hl=en&gl=US) on your phone, then enter your PC local IP address, if it shows your ping (not `Request timed out`), then your phone can connect to your PC
<img src="https://user-images.githubusercontent.com/32597776/166909874-661f439c-ea0c-4737-831e-c6d54c8b1a51.png" width=400/>

You can also try changing your network connection in your PC to `Private`:
1. Search and open `Network status` on Windows
2. Click `Properties`
<img src="https://user-images.githubusercontent.com/32597776/166910368-1a1ae8cc-14c8-4ea7-8734-bc5eab7f2529.png" width=400/>
3. Make sure that Private is ticked (as mentioned, do this only for a network you trust)
<img src="https://user-images.githubusercontent.com/32597776/166910410-176e9b81-9151-48dd-b24a-330e767c04f7.png" width=400/>

**Comment by SuspiciousLookingOwl** [comment]
Does the desktop application shows any received heart rate like this?
![image](https://user-images.githubusercontent.com/32597776/166908029-e4868660-2389-4705-91bc-ddc2da891ba7.png)

If not, then your phone probably can't connect to your PC

1. Make sure that your phone and PC is connected to the same network (e.g. connected to a same Wi-Fi)
2. Make sure that you entered the correct PC **local** (not public) IP address

To make sure that your phone can connect to your PC, you can use an app like [Ping](https://play.google.com/store/apps/details?id=net.WisdomStar.Ping&hl=en&gl=US) on your phone, then enter your PC local IP address, if it shows your ping (not `Request timed out`), then your phone can connect to your PC
<img src="https://user-images.githubusercontent.com/32597776/166909874-661f439c-ea0c-4737-831e-c6d54c8b1a51.png" width=400/>

You can also try changing your network connection in your PC to `Private`:
1. Search and open `Network status` on Windows
2. Click `Properties`
<img src="https://user-images.githubusercontent.com/32597776/166910912-0535eaa9-dc31-4f19-b03e-66eaa4944f7a.png" width=400/>

3. Make sure that Private is ticked (as mentioned, do this only for a network you trust)
<img src="https://user-images.githubusercontent.com/32597776/166910410-176e9b81-9151-48dd-b24a-330e767c04f7.png" width=400/>
